//
//  Theme.m
//  NNThemeKit
//
//  Created by NeroXie on 2025/11/6.
//

#import "Theme.h"
#import "ThemeIMP.h"
#import "ThemeModel.h"
#import "ThemeModeObserver.h"

NSString * const ThemeReloadThemeColorsNotification = @"theme.reloadThemeColors";
NSString * const ThemeChangedSuccessNotification = @"theme.changedSuccess";

#define THEME_MODE_OBSERVER ThemeModeObserver.sharedInstance

#define THEME_IMP ThemeIMP.sharedInstance
#define THEME_DATA THEME_IMP.data

#define THEME_ALPHA_IMPLEMENTATION(ALPHA_VALUE) \
+ (CGFloat)ALPHA_VALUE { \
/**/return THEME_DATA.alpha.ALPHA_VALUE; \
}

#define THEME_IMAGE_IMPLEMENTATION(IMAGE_VALUE) \
+ (CGFloat)IMAGE_VALUE { \
/**/return THEME_DATA.image.IMAGE_VALUE; \
}

#define THEME_TEXT_SIZE_IMPLEMENTATION(TEXT_SIZE_VALUE) \
+ (ThemeTextSize *)TEXT_SIZE_VALUE { \
/**/return THEME_DATA.text.TEXT_SIZE_VALUE; \
}

#define THEME_PADDING_IMPLEMENTATION(PADDING_VALUE) \
+ (CGFloat)PADDING_VALUE { \
/**/return THEME_DATA.padding.PADDING_VALUE; \
}

#define THEME_ICONFONT_IMPLEMENTATION(ICONFONT_VALUE) \
+ (CGFloat)ICONFONT_VALUE { \
/**/return THEME_DATA.iconfont.ICONFONT_VALUE; \
}

#define THEME_CIRCLE_IMPLEMENTATION(CIRCEL_VALUE) \
+ (CGFloat)CIRCEL_VALUE { \
/**/return THEME_DATA.circle.CIRCEL_VALUE; \
}

#define THEME_COLOR_IMPLEMENTATION(COLOR_VALUE) \
+ (UIColor *)COLOR_VALUE { \
/**/return ThemeIMP.sharedInstance.COLOR_VALUE; \
}

@implementation Theme

THEME_COLOR_IMPLEMENTATION(textBasicColorUnderLight)
THEME_COLOR_IMPLEMENTATION(textBasicColorUnderDark)
THEME_COLOR_IMPLEMENTATION(contrastingColorUnderLight)
THEME_COLOR_IMPLEMENTATION(contrastingColorUnderDark)

THEME_COLOR_IMPLEMENTATION(M1)
THEME_COLOR_IMPLEMENTATION(M2)
THEME_COLOR_IMPLEMENTATION(M3)
THEME_COLOR_IMPLEMENTATION(M4)
THEME_COLOR_IMPLEMENTATION(M5)
THEME_COLOR_IMPLEMENTATION(BG1)
THEME_COLOR_IMPLEMENTATION(BG2)
THEME_COLOR_IMPLEMENTATION(BG3)
THEME_COLOR_IMPLEMENTATION(BG4)
THEME_COLOR_IMPLEMENTATION(BG5)

THEME_ALPHA_IMPLEMENTATION(A1)
THEME_ALPHA_IMPLEMENTATION(A2)
THEME_ALPHA_IMPLEMENTATION(A3)
THEME_ALPHA_IMPLEMENTATION(A4)
THEME_ALPHA_IMPLEMENTATION(A5)
THEME_ALPHA_IMPLEMENTATION(A6)
THEME_ALPHA_IMPLEMENTATION(A7)
THEME_ALPHA_IMPLEMENTATION(A8)
THEME_ALPHA_IMPLEMENTATION(A9)
THEME_ALPHA_IMPLEMENTATION(A10)

THEME_TEXT_SIZE_IMPLEMENTATION(T1)
THEME_TEXT_SIZE_IMPLEMENTATION(T2)
THEME_TEXT_SIZE_IMPLEMENTATION(T3)
THEME_TEXT_SIZE_IMPLEMENTATION(T4)
THEME_TEXT_SIZE_IMPLEMENTATION(T5)
THEME_TEXT_SIZE_IMPLEMENTATION(T6)
THEME_TEXT_SIZE_IMPLEMENTATION(T7)
THEME_TEXT_SIZE_IMPLEMENTATION(T8)
THEME_TEXT_SIZE_IMPLEMENTATION(T9)
THEME_TEXT_SIZE_IMPLEMENTATION(T10)

THEME_PADDING_IMPLEMENTATION(P1)
THEME_PADDING_IMPLEMENTATION(P2)
THEME_PADDING_IMPLEMENTATION(P3)
THEME_PADDING_IMPLEMENTATION(P4)
THEME_PADDING_IMPLEMENTATION(P5)
THEME_PADDING_IMPLEMENTATION(P6)
THEME_PADDING_IMPLEMENTATION(P7)
THEME_PADDING_IMPLEMENTATION(P8)
THEME_PADDING_IMPLEMENTATION(P9)
THEME_PADDING_IMPLEMENTATION(P10)

THEME_ICONFONT_IMPLEMENTATION(IC1)
THEME_ICONFONT_IMPLEMENTATION(IC2)
THEME_ICONFONT_IMPLEMENTATION(IC3)
THEME_ICONFONT_IMPLEMENTATION(IC4)
THEME_ICONFONT_IMPLEMENTATION(IC5)
THEME_ICONFONT_IMPLEMENTATION(IC6)
THEME_ICONFONT_IMPLEMENTATION(IC7)
THEME_ICONFONT_IMPLEMENTATION(IC8)
THEME_ICONFONT_IMPLEMENTATION(IC9)
THEME_ICONFONT_IMPLEMENTATION(IC10)

THEME_CIRCLE_IMPLEMENTATION(C1)
THEME_CIRCLE_IMPLEMENTATION(C1_1)
THEME_CIRCLE_IMPLEMENTATION(C1_2)
THEME_CIRCLE_IMPLEMENTATION(C1_3)
THEME_CIRCLE_IMPLEMENTATION(C2)
THEME_CIRCLE_IMPLEMENTATION(C2_1)
THEME_CIRCLE_IMPLEMENTATION(C2_2)
THEME_CIRCLE_IMPLEMENTATION(C2_3)
THEME_CIRCLE_IMPLEMENTATION(C3)
THEME_CIRCLE_IMPLEMENTATION(C3_1)
THEME_CIRCLE_IMPLEMENTATION(C3_2)
THEME_CIRCLE_IMPLEMENTATION(C3_3)

THEME_IMAGE_IMPLEMENTATION(I1)
THEME_IMAGE_IMPLEMENTATION(I2)
THEME_IMAGE_IMPLEMENTATION(I3)
THEME_IMAGE_IMPLEMENTATION(I4)
THEME_IMAGE_IMPLEMENTATION(I5)
THEME_IMAGE_IMPLEMENTATION(I6)
THEME_IMAGE_IMPLEMENTATION(I7)
THEME_IMAGE_IMPLEMENTATION(I8)
THEME_IMAGE_IMPLEMENTATION(I9)
THEME_IMAGE_IMPLEMENTATION(I10)

+ (void)setup {
    [THEME_IMP setup];
}

+ (void)setupWithDelegate:(id<ThemeRuleDelegate>)delegate {
    THEME_IMP.delegate = delegate;
    [THEME_IMP setup];
}

+ (UIColor *)disableColorFromColor:(UIColor *)originalColor {
    return [THEME_IMP disableColorFromColor:originalColor];
}

+ (UIColor *)highLightedColorFromColor:(UIColor *)originalColor {
    return [THEME_IMP highLightedColorFromColor:originalColor];
}

+ (BOOL)checkIsDarkColor:(UIColor *)color {
    return [THEME_IMP checkIsDarkColor:color];
}

+ (BOOL)isDarkMode {
    if (@available(iOS 13.0, *)) {
        return THEME_MODE_OBSERVER.isDarkMode;
    } else {
        return NO;
    }
}

+ (void)changeThemeMode:(ThemeMode)themeMode {
    if (@available(iOS 13.0, *)) {
        [THEME_MODE_OBSERVER changeThemeMode:themeMode];
    }
}

//+ (UIStatusBarStyle)preferredStatusBarStyle {
//    if (@available(iOS 13.0, *)) {
//        return THEME_MODE_OBSERVER.preferredStatusBarStyle;
//    } else {
//        return UIStatusBarStyleDefault;
//    }
//}

+ (UIUserInterfaceStyle)currentUserInterfaceStyle {
    if (@available(iOS 13.0, *)) {
        return THEME_MODE_OBSERVER.currentUserInterfaceStyle;
    } else {
        return UIUserInterfaceStyleLight;
    }
}

@end
